### ISSUE TITLE
خطای time out 504

### ISSUE THREAD

**Issue by silverboy66000** [soroush-app/bot-php-sdk#3]
سلام 
موقع اجرای فایل 
get_messages.php
یا 
echo_bot.php
این خطا رو میده
اگه شناسه کاربر را مستقیم وارد بشه بقیه نمونه کد ها کار میکنه
برای این کار از کد های 
set_time_limit(500);
        ini_set('max_execution_time', 500); //300 seconds = 5 minutes
هم استفاده کردم ولی درست نشد
باتشکر

**Comment by rahel14** [comment]
دوست عزیر بهتر است شما هم مثل بنده قید سروش رو بزنید
منم سوالی داشتم که بعد 10 روز چه در اینجا چه از طریق سیستم تیکتشون کسی جوابگو نبود
شاید اگر انگلیسی سوالتون رو مطرح میکردید پاسخ میدادند!
بعد انتظار دارند مردم از تلگرام به اینگونه پیام رسانها با هزاران مشکلات کوچ کنند
البته این وسط من و شما متضرر نمیشیم چون من نوعی میتونم مجموعه 4 هزار نفری که قرار بود به سروش مهاجرت کنند رو توجیه کنم تا از یک پیام رسان خوب استفاده کنند. کما اینکه اینگونه هم شد

**Comment by amir-gholami** [comment]
> سلام
> موقع اجرای فایل
> get_messages.php
> یا
> echo_bot.php
> این خطا رو میده
> اگه شناسه کاربر را مستقیم وارد بشه بقیه نمونه کد ها کار میکنه
> برای این کار از کد های
> set_time_limit(500);
> ini_set('max_execution_time', 500); //300 seconds = 5 minutes
> هم استفاده کردم ولی درست نشد
> باتشکر

سلام 
برای اجرای فایل هایی نظیر
 `get_messages.php, echo_bot.php` 
می بایست از طریق خط فرمان یا کرون جاب این فایل ها را اجرا نمایید .

**Comment by amir-gholami** [comment]
> دوست عزیر بهتر است شما هم مثل بنده قید سروش رو بزنید
> منم سوالی داشتم که بعد 10 روز چه در اینجا چه از طریق سیستم تیکتشون کسی جوابگو نبود
> شاید اگر انگلیسی سوالتون رو مطرح میکردید پاسخ میدادند!
> بعد انتظار دارند مردم از تلگرام به اینگونه پیام رسانها با هزاران مشکلات کوچ کنند
> البته این وسط من و شما متضرر نمیشیم چون من نوعی میتونم مجموعه 4 هزار نفری که قرار بود به سروش مهاجرت کنند رو توجیه کنم تا از یک پیام رسان خوب استفاده کنند. کما اینکه اینگونه هم شد

سلام 
لطفا جزئیات درخواست ارسالی تان را اعلام کنید تا بررسی شود .

**Comment by silverboy66000** [comment]
> 
> 
> دوست عزیر بهتر است شما هم مثل بنده قید سروش رو بزنید
> منم سوالی داشتم که بعد 10 روز چه در اینجا چه از طریق سیستم تیکتشون کسی جوابگو نبود
> شاید اگر انگلیسی سوالتون رو مطرح میکردید پاسخ میدادند!
> بعد انتظار دارند مردم از تلگرام به اینگونه پیام رسانها با هزاران مشکلات کوچ کنند
> البته این وسط من و شما متضرر نمیشیم چون من نوعی میتونم مجموعه 4 هزار نفری که قرار بود به سروش مهاجرت کنند رو توجیه کنم تا از یک پیام رسان خوب استفاده کنند. کما اینکه اینگونه هم شد

بله همانگونه که می فرمائید امسال ما متضرر نخواهیم شد
این پروژه منه و نهایتا به کارفرمامم میگم امکان ارائه سرویس مد نظر از طریق ربات سروش وجود ندارد
.
.
.
منتها بنده با رویکرد مثبت به موضوع نگاه میکنم 
.
احتمالا اگه پیام رسانی فارسی هست لذا پشتیبانی از اون هم باید به صورت فارسی انجام شود

**Comment by silverboy66000** [comment]
> 
> 
> > سلام
> > موقع اجرای فایل
> > get_messages.php
> > یا
> > echo_bot.php
> > این خطا رو میده
> > اگه شناسه کاربر را مستقیم وارد بشه بقیه نمونه کد ها کار میکنه
> > برای این کار از کد های
> > set_time_limit(500);
> > ini_set('max_execution_time', 500); //300 seconds = 5 minutes
> > هم استفاده کردم ولی درست نشد
> > باتشکر
> 
> سلام
> برای اجرای فایل هایی نظیر
> `get_messages.php, echo_bot.php`
> می بایست از طریق خط فرمان یا کرون جاب این فایل ها را اجرا نمایید .

آیا مشکل خطایی که مطرح کردم 
با کرون جاب حل میشود ؟
چون سوال من قبل از کرون هست
و اونم این که اصولا برای اجرای این فایل ها سرور خطای 503 میدهد
لطفا راهنمایی بفرمائید
ممنون

**Comment by amir-gholami** [comment]
@silverboy66000 
اصولا این نوع  خطا ها در ارتباط با اجرا فایل ها توسط وب سرور ها می باشد 
با اجرای کد توسط کرون جاب مشکل تان حل خواهد شد .

**Comment by silverboy66000** [comment]
> 
> 
> @silverboy66000
> اصولا این نوع خطا ها در ارتباط با اجرا فایل ها توسط وب سرور ها می باشد
> با اجرای کد توسط کرون جاب مشکل تان حل خواهد شد .

من همین کار رو هم کردم 
اما همچنان خطا دارم

  //phpinfo();
        $bot_token = 'YhZrFjrARGYYa6L49idU0BOgI7L-KAwEgd01A-OIWejNXXOjd4kmUOZTnjO7fee-C-YwHgo4e8iNPo5CkZArcl3Ohf_V7Gk99HCvvBHBUsjF9Yga1QYf3egvYdTtfd_B9TnspFD8oz_1IVr4';

        $bot = new Soroush\Client($bot_token);


        $messages = $bot->getMessages();
        foreach ($messages as $message) {
            $data = $message->getData();
            echo "New Message Received !" . PHP_EOL . "From: " . $data['from'] . PHP_EOL . "Type: " . $data['type'] . PHP_EOL;
                echo "Body: " . $data['body'] . PHP_EOL;
        }

داخل کلاس کلاینت 
در قسمت 
$buffer .= $body->read(1);

            if (preg_match(self::END_OF_MESSAGE, $buffer)) {
بعد از مدت طولانی لودینگ نهایتا خطای 
500 میده
اینم متنش
Request Timeout
This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'.

**Comment by silverboy66000** [comment]
بعد از ساعت ها این خطا رو میده:


Error creating resource: [message] fopen(): SSL: Connection reset by peer
[file] /home/jamkaran/domains/silverboy66000.ir/public_html/test/silverboy66000/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
[message] fopen(https://bot.sapp.ir/YhZrFjrARGYYa6L49idU0BOgI7L-KAwEgd01A-OIWejNXXOjd4kmUOZTnjO7fee-C-YwHgo4e8iNPo5CkZArcl3Ohf_V7Gk99HCvvBHBUsjF9Yga1QYf3egvYdTtfd_B9TnspFD8oz_1IVr4/getMessage): failed to open stream: HTTP request failed!
[file] /home/silverboy66000/domains/silverboy66000.ir/public_html/test/silverboy66000/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323

**Comment by silverboy66000** [comment]
البته من این پروژه رو با لاراول آوردم بالا 

تایم اوت سرور رو هم بردم بالا

**Comment by amir-gholami** [comment]
> > @silverboy66000
> > اصولا این نوع خطا ها در ارتباط با اجرا فایل ها توسط وب سرور ها می باشد
> > با اجرای کد توسط کرون جاب مشکل تان حل خواهد شد .
> 
> من همین کار رو هم کردم
> اما همچنان خطا دارم
> 
> //phpinfo();
> $bot_token = '...';
> 
> ```
>     $bot = new Soroush\Client($bot_token);
> 
> 
>     $messages = $bot->getMessages();
>     foreach ($messages as $message) {
>         $data = $message->getData();
>         echo "New Message Received !" . PHP_EOL . "From: " . $data['from'] . PHP_EOL . "Type: " . $data['type'] . PHP_EOL;
>             echo "Body: " . $data['body'] . PHP_EOL;
>     }
> ```
> 
> داخل کلاس کلاینت
> در قسمت
> $buffer .= $body->read(1);
> 
> ```
>         if (preg_match(self::END_OF_MESSAGE, $buffer)) {
> ```
> 
> بعد از مدت طولانی لودینگ نهایتا خطای
> 500 میده
> اینم متنش
> Request Timeout
> This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'.

مطمئن هستید که از طریق کرون جاب در حال اجرای کد هستید ؟ خطای 
 Request Timeout
 و خطای 500
مربوط به اجرا از سمت وب سرور است 
روی 0 ( بی نهایت) قراردارد max_execution_time مقدار CLI در حالت اجرا توسط

**Comment by silverboy66000** [comment]
> 
> 
> > > @silverboy66000
> > > اصولا این نوع خطا ها در ارتباط با اجرا فایل ها توسط وب سرور ها می باشد
> > > با اجرای کد توسط کرون جاب مشکل تان حل خواهد شد .
> > 
> > 
> > من همین کار رو هم کردم
> > اما همچنان خطا دارم
> > //phpinfo();
> > $bot_token = '...';
> > ```
> >     $bot = new Soroush\Client($bot_token);
> > 
> > 
> >     $messages = $bot->getMessages();
> >     foreach ($messages as $message) {
> >         $data = $message->getData();
> >         echo "New Message Received !" . PHP_EOL . "From: " . $data['from'] . PHP_EOL . "Type: " . $data['type'] . PHP_EOL;
> >             echo "Body: " . $data['body'] . PHP_EOL;
> >     }
> > ```
> > داخل کلاس کلاینت
> > در قسمت
> > $buffer .= $body->read(1);
> > ```
> >         if (preg_match(self::END_OF_MESSAGE, $buffer)) {
> > ```
> > بعد از مدت طولانی لودینگ نهایتا خطای
> > 500 میده
> > اینم متنش
> > Request Timeout
> > This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'.
> 
> مطمئن هستید که از طریق کرون جاب در حال اجرای کد هستید ؟ خطای
> Request Timeout
> و خطای 500
> مربوط به اجرا از سمت وب سرور است
> روی 0 ( بی نهایت) قراردارد max_execution_time مقدار CLI در حالت اجرا توسط

میتونم خواهش کنم دستور کرون جابی که منظورتونه رو ارسال کنید ؟
مربوط به پنل دایرکت ادمین خودش میتونه مستقیم اجرا کنه میشه هم از کد استفاده کرد 
اون حالتی که مد نظر شماست رو میخواستم خواهش کنم بفرستید

**Comment by silverboy66000** [comment]
متاسفانه مهم ترین قسمت بات که شروع هست گیر کردم در حالی که در لوکال هاست کار کرد و من تونستم بقیه قسمت ها رو اجرا کنم ممنون میشم همراهی کنید تا این قسمت حل بشه

**Comment by amir-gholami** [comment]
مکاتبه نمایید تا بررسی داشته باشیم. `composer.json` لطفا از طریق آدرس ایمیل اعلام شده در فایل
