### ISSUE TITLE
Get Channel Post

### ISSUE THREAD

**Issue by pesar368** [soroush-app/bot-php-sdk#7]
سلام
چطوری میتونم با استفاده ربات یا رابط سروش ، مطالب و پست های یک کانال عمومی رو استخراج کنم ؟
ممنون

**Comment by amir-gholami** [comment]
سلام 
در ارائه اولیه پلتفرم بات سروش ارائه این امکان مقدور نیست . به احتمال در ارائه های بعدی این امکان اضافه خواهد شد .
