### ISSUE TITLE
بدون Composer

### ISSUE THREAD

**Issue by famousman** [soroush-app/bot-php-sdk#8]
سلام میخوام از SDK بدون Composer بکار بگیرم.
خطا زیر رو داد
Fatal error: Class 'GuzzleHttp\Client' not found in /home/hostname/public_html/bots/first/sdk/Client.php on line 33

**Comment by amir-gholami** [comment]
سلام 
در [این](https://github.com/soroush-app/bot-php-sdk/releases) بخش می توانید نسخه ای که عملیات نصب composer
قبلا در آن انجام شده است را دانلود کنید .
